name: First Demo Action

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo 'Action Started'
      - name: Checkout
        uses: actions/checkout@v4

      - name: run a one-line script
        run: echo Hello, world!
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: list files
        run: ls ${GITHUB_WORKSPACE}
      - name: print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Action Completed
        run: echo 'Action Completed'
        